string command
string mode
string attitude_mode
bool enabled
bool dual_arm
string preferred_side
int32 speed_index
float32[] speed_levels
int32 stick_deadzone
float32 cartesian_position_step
float32 cartesian_rotation_step
float32 cartesian_max_speed
float32 cartesian_max_angular_speed
float32 joint_angle_step
int32 joint_max_speed
int32 joint_acceleration
int32 joint_deceleration
float32 attitude_position_speed_mm_s
float32 attitude_mode2_position_speed_mm_s
float32 attitude_rotation_gain
float32 attitude_mode2_rotation_gain
float32 attitude_joint_max_speed
float32 attitude_joint_acceleration
float32 attitude_joint_deceleration
float32 workspace_min_radius
float32 workspace_max_radius
float32 workspace_min_z
float32 workspace_max_z
---
bool success
bool running
string mode
int32 attitude_mode
string message
string status_json
string input_json
